### ISSUE TITLE
Extensions page results in 500 error

### ISSUE THREAD

**Issue by SamKr** [dorel14/3CX-Cdr-Server#67]
**Describe the bug**
When going to the `/app/extensions/` page, a server error 500 error is shown:

`ValueError: If using all scalar values, you must pass an index`

The following error is shown in the webapp container's log:

```shell
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/opt/venv/lib/python3.12/site-packages/starlette/_utils.py", line 87, in collapse_excgroups
  |     yield
  |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 190, in __call__
  |     async with anyio.create_task_group() as task_group:
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/opt/venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/opt/venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/opt/venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/opt/venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/opt/venv/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    |     raise exc
    |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    |     with collapse_excgroups():
    |          ^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    |     self.gen.throw(value)
    |   File "/opt/venv/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    |     raise exc
    |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/opt/venv/lib/python3.12/site-packages/nicegui/middlewares.py", line 10, in dispatch
    |     response = await call_next(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    |     raise app_exc
    |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    |     await responder(scope, receive, send)
    |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    |     await self.app(scope, receive, self.send_with_gzip)
    |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/opt/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    |     raise exc
    |   File "/opt/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    |     await route.handle(scope, receive, send)
    |   File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    |     await self.app(scope, receive, send)
    |   File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "/opt/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    |     raise exc
    |   File "/opt/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    |     response = await func(request)
    |                ^^^^^^^^^^^^^^^^^^^
    |   File "/opt/venv/lib/python3.12/site-packages/fastapi/routing.py", line 299, in app
    |     raise e
    |   File "/opt/venv/lib/python3.12/site-packages/fastapi/routing.py", line 294, in app
    |     raw_response = await run_endpoint_function(
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/opt/venv/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    |     return await dependant.call(**values)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/opt/venv/lib/python3.12/site-packages/nicegui/page.py", line 112, in decorated
    |     result = func(*dec_args, **dec_kwargs)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/webapp/ui_new/extensions.py", line 110, in extension_page
    |     df = pd.DataFrame(extensions)
    |          ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/opt/venv/lib/python3.12/site-packages/pandas/core/frame.py", line 778, in __init__
    |     mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/opt/venv/lib/python3.12/site-packages/pandas/core/internals/construction.py", line 503, in dict_to_mgr
    |     return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/opt/venv/lib/python3.12/site-packages/pandas/core/internals/construction.py", line 114, in arrays_to_mgr
    |     index = _extract_index(arrays)
    |             ^^^^^^^^^^^^^^^^^^^^^^
    |   File "/opt/venv/lib/python3.12/site-packages/pandas/core/internals/construction.py", line 667, in _extract_index
    |     raise ValueError("If using all scalar values, you must pass an index")
    | ValueError: If using all scalar values, you must pass an index
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/venv/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
         ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/opt/venv/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/nicegui/middlewares.py", line 10, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/opt/venv/lib/python3.12/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/nicegui/page.py", line 112, in decorated
    result = func(*dec_args, **dec_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/webapp/ui_new/extensions.py", line 110, in extension_page
    df = pd.DataFrame(extensions)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/pandas/core/frame.py", line 778, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/pandas/core/internals/construction.py", line 503, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/pandas/core/internals/construction.py", line 114, in arrays_to_mgr
    index = _extract_index(arrays)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/pandas/core/internals/construction.py", line 667, in _extract_index
    raise ValueError("If using all scalar values, you must pass an index")
ValueError: If using all scalar values, you must pass an index
```

**Comment by SamKr** [comment]
The rest of the system is working fine, and the db is filling with call logs.

**Comment by dorel14** [comment]
Happy to ear call logs are fine, 

Do you use dev version or master ? 

For the moment, master is not completly ok for the ui part

**Comment by SamKr** [comment]
I switched to the dev branch (looking good!). I still get an error on extensions, a different one this time:

`TypeError: AgGrid.__init__() missing 1 required positional argument: 'options'`

And in the logs:

```shell
webapp          | TypeError: AgGrid.__init__() missing 1 required positional argument: 'options'
webapp          | ERROR:    Exception in ASGI application
webapp          |   + Exception Group Traceback (most recent call last):
webapp          |   |   File "/opt/venv/lib/python3.12/site-packages/starlette/_utils.py", line 87, in collapse_excgroups
webapp          |   |     yield
webapp          |   |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 190, in __call__
webapp          |   |     async with anyio.create_task_group() as task_group:
webapp          |   |   File "/opt/venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
webapp          |   |     raise BaseExceptionGroup(
webapp          |   | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
webapp          |   +-+---------------- 1 ----------------
webapp          |     | Traceback (most recent call last):
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
webapp          |     |     result = await app(  # type: ignore[func-returns-value]
webapp          |     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
webapp          |     |     return await self.app(scope, receive, send)
webapp          |     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
webapp          |     |     await super().__call__(scope, receive, send)
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
webapp          |     |     await self.middleware_stack(scope, receive, send)
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
webapp          |     |     raise exc
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
webapp          |     |     await self.app(scope, receive, _send)
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
webapp          |     |     with collapse_excgroups():
webapp          |     |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
webapp          |     |     self.gen.throw(value)
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
webapp          |     |     raise exc
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
webapp          |     |     response = await self.dispatch_func(request, call_next)
webapp          |     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/nicegui/middlewares.py", line 10, in dispatch
webapp          |     |     response = await call_next(request)
webapp          |     |                ^^^^^^^^^^^^^^^^^^^^^^^^
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
webapp          |     |     raise app_exc
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
webapp          |     |     await self.app(scope, receive_or_disconnect, send_no_error)
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 24, in __call__
webapp          |     |     await responder(scope, receive, send)
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 44, in __call__
webapp          |     |     await self.app(scope, receive, self.send_with_gzip)
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
webapp          |     |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
webapp          |     |     raise exc
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
webapp          |     |     await app(scope, receive, sender)
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
webapp          |     |     await self.middleware_stack(scope, receive, send)
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
webapp          |     |     await route.handle(scope, receive, send)
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
webapp          |     |     await self.app(scope, receive, send)
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
webapp          |     |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
webapp          |     |     raise exc
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
webapp          |     |     await app(scope, receive, sender)
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
webapp          |     |     response = await func(request)
webapp          |     |                ^^^^^^^^^^^^^^^^^^^
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/fastapi/routing.py", line 299, in app
webapp          |     |     raise e
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/fastapi/routing.py", line 294, in app
webapp          |     |     raw_response = await run_endpoint_function(
webapp          |     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
webapp          |     |     return await dependant.call(**values)
webapp          |     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webapp          |     |   File "/opt/venv/lib/python3.12/site-packages/nicegui/page.py", line 112, in decorated
webapp          |     |     result = func(*dec_args, **dec_kwargs)
webapp          |     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webapp          |     |   File "/webapp/ui_new/pages/extensions_view.py", line 149, in extension_page
webapp          |     |     ui.aggrid().from_pandas(emptydf).classes('grid-flow-col')
webapp          |     |     ^^^^^^^^^^^
webapp          |     | TypeError: AgGrid.__init__() missing 1 required positional argument: 'options'
webapp          |     +------------------------------------
webapp          | 
webapp          | During handling of the above exception, another exception occurred:
webapp          | 
webapp          | Traceback (most recent call last):
webapp          |   File "/opt/venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
webapp          |     result = await app(  # type: ignore[func-returns-value]
webapp          |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webapp          |   File "/opt/venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
webapp          |     return await self.app(scope, receive, send)
webapp          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webapp          |   File "/opt/venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
webapp          |     await super().__call__(scope, receive, send)
webapp          |   File "/opt/venv/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
webapp          |     await self.middleware_stack(scope, receive, send)
webapp          |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
webapp          |     raise exc
webapp          |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
webapp          |     await self.app(scope, receive, _send)
webapp          |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
webapp          |     with collapse_excgroups():
webapp          |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
webapp          |     self.gen.throw(value)
webapp          |   File "/opt/venv/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
webapp          |     raise exc
webapp          |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
webapp          |     response = await self.dispatch_func(request, call_next)
webapp          |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webapp          |   File "/opt/venv/lib/python3.12/site-packages/nicegui/middlewares.py", line 10, in dispatch
webapp          |     response = await call_next(request)
webapp          |                ^^^^^^^^^^^^^^^^^^^^^^^^
webapp          |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
webapp          |     raise app_exc
webapp          |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
webapp          |     await self.app(scope, receive_or_disconnect, send_no_error)
webapp          |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 24, in __call__
webapp          |     await responder(scope, receive, send)
webapp          |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 44, in __call__
webapp          |     await self.app(scope, receive, self.send_with_gzip)
webapp          |   File "/opt/venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
webapp          |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
webapp          |   File "/opt/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
webapp          |     raise exc
webapp          |   File "/opt/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
webapp          |     await app(scope, receive, sender)
webapp          |   File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
webapp          |     await self.middleware_stack(scope, receive, send)
webapp          |   File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
webapp          |     await route.handle(scope, receive, send)
webapp          |   File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
webapp          |     await self.app(scope, receive, send)
webapp          |   File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
webapp          |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
webapp          |   File "/opt/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
webapp          |     raise exc
webapp          |   File "/opt/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
webapp          |     await app(scope, receive, sender)
webapp          |   File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
webapp          |     response = await func(request)
webapp          |                ^^^^^^^^^^^^^^^^^^^
webapp          |   File "/opt/venv/lib/python3.12/site-packages/fastapi/routing.py", line 299, in app
webapp          |     raise e
webapp          |   File "/opt/venv/lib/python3.12/site-packages/fastapi/routing.py", line 294, in app
webapp          |     raw_response = await run_endpoint_function(
webapp          |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webapp          |   File "/opt/venv/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
webapp          |     return await dependant.call(**values)
webapp          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webapp          |   File "/opt/venv/lib/python3.12/site-packages/nicegui/page.py", line 112, in decorated
webapp          |     result = func(*dec_args, **dec_kwargs)
webapp          |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webapp          |   File "/webapp/ui_new/pages/extensions_view.py", line 149, in extension_page
webapp          |     ui.aggrid().from_pandas(emptydf).classes('grid-flow-col')
webapp          |     ^^^^^^^^^^^
```

**Comment by SamKr** [comment]
Nevermind, found the fix, I'll submit a PR
