### ISSUE TITLE
Both extension and queues import don't work

### ISSUE THREAD

**Issue by SamKr** [dorel14/3CX-Cdr-Server#78]
Uploading works now, but importing gives an error. They both have a different error.

For queues:

```shell
webapp          | 'str' object has no attribute 'to_json'
webapp          | Traceback (most recent call last):
webapp          |   File "/opt/venv/lib/python3.12/site-packages/nicegui/events.py", line 419, in wait_for_result
webapp          |     await result
webapp          |   File "/webapp/ui_new/pages/queues_view.py", line 62, in click_import
webapp          |     response = await run.io_bound(post_queues, data_files)
webapp          |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webapp          |   File "/opt/venv/lib/python3.12/site-packages/nicegui/run.py", line 74, in io_bound
webapp          |     return await _run(thread_pool, callback, *args, **kwargs)
webapp          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webapp          |   File "/opt/venv/lib/python3.12/site-packages/nicegui/run.py", line 52, in _run
webapp          |     return await loop.run_in_executor(executor, partial(callback, *args, **kwargs))
webapp          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webapp          |   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
webapp          |     result = self.fn(*self.args, **self.kwargs)
webapp          |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webapp          |   File "/webapp/myhelpers/queues_import.py", line 22, in post_queues
webapp          |     list_of_jsons = queues.to_json(orient='records', lines=True).splitlines()
webapp          |                     ^^^^^^^^^^^^^^
webapp          | AttributeError: 'str' object has no attribute 'to_json'

```

This looks to be because it's provided as a string instead of DataFrame.

For extensions:

```
webapp          | Erreur 422 (Unprocessable Entity) lors de la récupération de l'extension: 422 Client Error: Unprocessable Entity for url: http://webapi:8000/v1/extensions
```

The import code for `extensions_import.py` and `queues_import.py` differ, so before I try to debug, could you point me in the right direction of what you had in mind?

**Comment by dorel14** [comment]
hello , on witch version are you ?

**Comment by SamKr** [comment]
> When creating an issue , can you tell me witch branch you're using ?

Of course

> I solved the bug

Works like a charm, thanks @dorel14
